# Generated by Django 3.1.6 on 2021-02-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210222_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='complete',
            new_name='comp',
        ),
    ]
